---

- name: Установка zabbix-agent Debian
  apt:
    name: zabbix-agent
    state: latest
  when:
    ansible_os_family == "Debian"

- name: Копирование репозитория
  uri:
    url: https://repo.zabbix.com/zabbix/6.4/rhel/7/x86_64/zabbix-release-6.4-1.el7.noarch.rpm 
    dest: /tmp 
  when:
    ansible_os_family == "RedHat"

- name: Установка репозитория
  raw: rpm -Uvh /tmp/zabbix-release-6.4-1.el7.noarch.rpm
  args:
    executable: /bin/bash  
  when:
    ansible_os_family == "RedHat"
  ignore_errors: yes

- name: Установка zabbix-agent Cetntos
  yum:
    name: zabbix-agent
    state: latest
  when:
    ansible_os_family == "RedHat"
  ignore_errors: yes

- name: Настройка адреса zabbix-server
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server=127.0.0.1$'
    replace: 'Server=10.10.0.1'

- name: Перезапуск zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
